In [13]:
import pandas as pd
import numpy as np
 
kc = pd.read_csv("kc_house_data.csv")


In [14]:
kc.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [15]:
from sklearn.linear_model import LogisticRegression

In [6]:
print(kc.date)

0        20141013T000000
1        20141209T000000
2        20150225T000000
3        20141209T000000
4        20150218T000000
5        20140512T000000
6        20140627T000000
7        20150115T000000
8        20150415T000000
9        20150312T000000
10       20150403T000000
11       20140527T000000
12       20140528T000000
13       20141007T000000
14       20150312T000000
15       20150124T000000
16       20140731T000000
17       20140529T000000
18       20141205T000000
19       20150424T000000
20       20140514T000000
21       20140826T000000
22       20140703T000000
23       20140516T000000
24       20141120T000000
25       20141103T000000
26       20140626T000000
27       20141201T000000
28       20140624T000000
29       20150302T000000
              ...       
21583    20140610T000000
21584    20141202T000000
21585    20140828T000000
21586    20141015T000000
21587    20150305T000000
21588    20141113T000000
21589    20140910T000000
21590    20140514T000000
21591    20141002T000000


In [37]:

Y = kc.yr_renovated
X = kc.drop(['yr_renovated','date'], axis = 1)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0) # 80%のデータを学習データに、20%を検証データにする

log_model = LogisticRegression()
log_model.fit(X, Y)
log_model.score(X, Y)

/Users/senna/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/senna/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9577106371165502

In [38]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split


In [44]:
Y_pred = log_model.predict(X_test)

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, f1_score

print('confusion matrix = \n', confusion_matrix(y_true=Y_test, y_pred=Y_pred))
print('accuracy = ', accuracy_score(y_true=Y_test, y_pred=Y_pred))
print('precision = ', precision_score(y_true=Y_test, y_pred=Y_pred, average = 'micro'))
print('recall = ', recall_score(y_true=Y_test, y_pred=Y_pred, average = 'micro'))
print('f1 score = ', f1_score(y_true=Y_test, y_pred=Y_pred, average = 'micro'))

confusion matrix = 
 [[4166    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 ...
 [   4    0    0 ...    0    0    0]
 [  18    0    0 ...    0    0    0]
 [   3    0    0 ...    0    0    0]]
accuracy =  0.9636826278047652
precision =  0.9636826278047652
recall =  0.9636826278047652
f1 score =  0.9636826278047652
